[DEFAULT]
bantime = 600
findtime = 60
maxretry = 5

[blaqliq-ssh]
enabled = true
port = ssh
logpath = /var/log/auth.log
maxretry = 3
findtime = 60
bantime = 600

[blaqliq-bruteforce]
enabled = true
port = all
logpath = /var/log/auth.log
maxretry = 5
findtime = 60
bantime = 300
